- src/resources/swagger.yaml
- src/routes/applications.ts
csa column is required in daco csv; value is always `true`
> 93 - Add csa column to users csv

- src/resources/swagger.yaml
Adds daco2ego email to swagger docs for #95
> 95 - Add daco email to swagger. reorder swagger sections

- src/domain/state.ts
- src/domain/validations.ts
When duplicate publication urls are added, API will respond with an error instead of removing the duplicate strings.
> 🐛 150 - Send error for dup publication urls. do not remove dup urls

- src/domain/state.ts
- src/test/state.spec.ts
fixes bug where app can get stuck in `REVISIONS REQUESTED` state when only signature section is selected for revisions
adds test
> 🐛 281 - allow upload when signature only has revisions requested

- src/config.ts
- src/routes/applications.ts
- src/test/encryption.spec.ts
- src/utils/constants.ts
- src/utils/misc.ts
Necessary for #95 
Needed to output encrypted content as base64 to allow decryption with `openssl` command
Fixes encryption key format
Fixes encryption key arg in cipher creation
Adds `openssl` command example to test for reference
Splits encrypted content string into 64-char lines to avoid 🐛iness in `openssl -A`
Remove secrets reference for `DCC_MAILING_LIST` var, will be added in helm values
> 🐛 Fix encoding to allow openssl decryption on command line

- src/domain/service.ts
- src/domain/state.ts
- src/test/state.spec.ts
- src/utils/misc.ts
Adds app config to state manager constructor to avoid extra async calls for some helper functions
Updates `getAttestationByDate` to use configured attestation period
Updates tests with mock config
> Add config to state manager class. use configurable attestation vals

- src/domain/model.ts
- src/domain/service.ts
Filter for approved apps with attestationByUtc of today or later, to catch any pauseable apps that are missed due to a state change error
- also adds `pauseReason` to model, this was missed in a previous pr
> fix pauseable app date filter

- src/domain/interface.ts
- src/domain/service.ts
- src/domain/state.ts
- src/utils/misc.ts
Adds most recent `PAUSED` update event from `updates` list to single app and app summary responses so FE doesn't need to find the value. The pause event is usually not the same as the `attestationByUtc` date, as the batch job runs the next day.
- also avoids the assumption that every pause event going forward is due to missed attestation
> ✨ 340 - add lastPausedAtUtc to app and summary responses

- migrations/20220826193604-remove_able_to_renew_field.js
- src/domain/interface.ts
- src/domain/model.ts
- src/domain/service.ts
- src/domain/state.ts
- src/test/state.spec.ts
- src/test/utils.spec.ts
- src/utils/calculations.ts
change `ableToRenew` to calculated field
- migration to remove this field from the db
- add the field to `Application` and `ApplicationSummary` response
- create util function to calculate renewable status
- add tests
> 🗃️ 292 - calculable ableToRenew field

- src/emails/application-paused.ts
use pause date from pause event instead of calculated attest by date if available
> 💬 229 - use correct pause date in paused email

- src/domain/interface.ts
- src/domain/service.ts
- src/domain/state.ts
- src/domain/validations.ts
- src/test/state.spec.ts
Adds `isRenewal` to update application request
Creates renewal transition for renewable `APPROVED` applications*
Adds `isRenewal` field to `ApplicationSummary` response
Adds state tests
* handling transition for `EXPIRED` applications will be implemented in https://github.com/icgc-argo/dac-api/issues/252
> ✨ 253 - add renewal transition for approved apps

- package-lock.json
- package.json
- src/domain/interface.ts
- src/domain/service/applications/index.ts
- src/domain/state.ts
- src/test/state.spec.ts
Updates ego-token-middleware to `2.4.1`
Adds function to extract submitter info with verified email, to account for middleware type changes.
Throws error if email is not present when creating an application.
> 🏷️ Token middleware fix

- src/jobs/pauseAppCheck.ts
Was using the old application object in the email flag op, so state was getting reset to `APPROVED` !
> fix incorrect appObj arg

- dac-api-compose/docker-compose.yaml
- src/domain/interface.ts
- src/domain/model.ts
- src/domain/service/applications/index.ts
- src/domain/service/applications/search.ts
- src/domain/service/files.ts
- src/domain/state.ts
- src/resources/swagger.yaml
- src/routes/applications.ts
- src/storage/index.ts
- src/test/state.spec.ts
- src/test/utils.spec.ts
- src/utils/calculations.ts
Adds new `POST` endpoint for creating a renewal
- adds `renewalAppId` to source application and `sourceAppId` to renewal app, for tracking. Adds these to search values
- adds `renewalPeriodEndDateUtc` to track when a renewal app should be closed, if it has been approved or submitted for review
- uses mongoose `withTransaction` to allow rollback of a created renewal if any of the db ops fails
- updates docker-compose mongo setup to use replicaSet to allow mongoose transactions in local development
- renewal apps will copy over ethics docs object ids, so check added to any delete actions to prevent file deletion if the objectId is referenced in another application
- updates swagger
- adds `PAUSED` state to allowed states fore `isRenewable`
- handling for renewals that are closed before …
> ✨ 364 - renewal request

- src/domain/service/applications/index.ts
- src/domain/state.ts
- src/utils/errors.ts
Fixes issue where the server would return a 500 error when an app transitioned between `DRAFT` and `SIGN AND SUBMIT`, because these cases were not included in the switch
> 🐛 392 - add missing state cases to onStateChange call. Add 400 error name

- src/domain/service/applications/index.ts
- src/domain/service/files.ts
Fixes the incorrect negation on the isReferenced calls - promises are truthy so the result was always false! 🤦‍♀️ 
Also adds `CLOSED` update check to the close renewal logic - this flow should only occur when a renewal is being closed
* I created the ticket in the wrong repo, will update that
> fix isEthicsDocReferenced result usage

- src/domain/service/applications/index.ts
- src/domain/state.ts
Triggers revisions email when the only section that requires a revision is signature, because in this scenario the app state is `SIGN AND SUBMIT`, not `REVISIONS REQUESTED`
> 🐛 402 - trigger revisions email when requested on signature only

- src/domain/service/applications/index.ts
- src/server.ts
Add checks for null `renewalAppId` and `sourceAppId` when unlinking a unsubmitted renewal from its source application. Transaction will roll back.
- fixes incorrect syntax in migration logger statements
> 🐛 395 - Verify renewal and source app ids are removed on unlink call

- src/domain/service/applications/index.ts
`break` was _breaking_ the intended `for...await` functionality
(stopped the loop from iterating over multiple items in the array, whoops)
> 🐛 414 - fix ethics doc reference iteration

- src/domain/interface.ts
- src/domain/service/applications/search.ts
- src/domain/state.ts
- src/utils/calculations.ts
Adds `sourceRenewalPeriodEndDateUtc` as a calculated field for the FE to use, to keep renewal period consistent.
- FE no longer needs to track a `DAYS_POST_EXPIRY` env var (https://github.com/icgc-argo/dac-ui/pull/686)
> ✨ 419 - add renewal period end date as calculated field for FE

- src/jobs/ega/fetchPublicKey.ts
Dockerfile is using node:16, which doesn't include `fetch`. Need to import as `node-fetch` for the ega public key request.
> import fetch for node 16

- src/jobs/ega/services/permissions.ts
Removes the if clause for `existingPermission.length` as this prevents permissions being added when a user on the approved list has no existing ones.
> Fixes failure to add permissions when none exist
