icgc-argo/dac-api

src/domain/service.ts, src/domain/state.ts, src/emails/approved.ts, src/emails/common.ts, src/emails/review.ts, src/emails/submitted.ts, src/resources/swagger.yaml, src/test/emails.spec.ts, src/test/state.spec.ts
create email components
implement submitted email
=> submitted emails

package-lock.json, package.json, src/app.ts, src/domain/interface.ts, src/domain/model.ts, src/domain/service.ts, src/domain/state.ts, src/resources/swagger.yaml, src/routes/applications.ts, src/server.ts, src/storage/index.ts, src/utils/misc.ts
rename signedAt to uploadedAt
fix health endpoint
=> zip package endpoint

src/domain/interface.ts, src/domain/service.ts, src/domain/state.ts, src/domain/validations.ts, src/routes/applications.ts, src/utils/misc.ts
#67 
plus handle unlocking incomplete sections if needed
=> #67 fix representative status in revision requests

src/domain/state.ts, src/test/state.spec.ts, src/utils/misc.ts
=> fix collaborator update

src/domain/interface.ts, src/domain/model.ts, src/domain/state.ts, src/domain/validations.ts
keep track of updates on collaborator/representative
fixes #67
=> add updated state to sections

src/domain/service.ts, src/emails/collaborator-added.ts, src/emails/common.ts, src/emails/ethics-letter.ts, src/emails/review-new.ts, src/emails/review-revised.ts, src/routes/applications.ts
collaborator added email
ethics letter submitted email
=> more emails

src/domain/state.ts, src/domain/validations.ts
=> fix issues 94, 83

package.json, src/domain/state.ts, src/emails/application-approved.ts, src/emails/revisions-requested.ts, src/test/emails.spec.ts, src/test/state.spec.ts
=> 🔖 Rc/0.26.0

package.json
=> 🔖 Rc/0.28.0

src/domain/validations.ts, src/test/state.spec.ts
Adds `validateRequired` check for `applicant.website`
=> 🐛 285 - Add required validation for applicant website

src/domain/interface.ts, src/domain/service.ts, src/routes/applications.ts, src/utils/misc.ts
Adds endpoint for exporting daco approved users csv.
Adds defaultSort to search function
*Need to verify csv filename and expected value for `changed` column, but these are not blockers for the main work
=> ✨ 93 - daco controlled users file

src/domain/validations.ts
Make sure website is required only for applicant
=> 🐛 285 - fix website required where it is not

package.json, src/domain/interface.ts, src/domain/model.ts, src/domain/state.ts, src/domain/validations.ts, src/emails/application-approved.ts, src/test/state.spec.ts
#93 
[dac-ui-285](https://github.com/icgc-argo/dac-ui/issues/285)
=> 🔖 Rc/0.29.0

src/resources/swagger.yaml, src/routes/applications.ts
Adds `/export/approved-users/` to swagger docs
=> 📝 add approved users export endpoint to swagger

src/domain/interface.ts, src/domain/state.ts
Updates expected appendixes, formatting
=> 💬 136 - Update expected appendix agreements

src/config.ts, src/domain/service.ts, src/emails/application-approved.ts, src/emails/collaborator-notification.ts, src/emails/common.ts, src/emails/revisions-requested.ts, src/emails/submitted.ts, src/test/emails.spec.ts, src/utils/constants.ts
Minor text updates and url changes.
Adds `bcc` to `sendEmail`
I added comments for everything that is an actual change, since there's a lot of formatting!
=> 💬 140 - email content updates

src/emails/revisions-requested.ts
Order revisions sections in table to match ui sections order.
=> 💄 118 - specify order for revisions section table

.env.example, src/app.ts
add global file upload limit with client resp
=> Add global file upload limit with client response

.env.example, src/config.ts, src/domain/service.ts, src/routes/applications.ts, src/test/encryption.spec.ts, src/utils/constants.ts, src/utils/misc.ts
Adds encrypted email endpoint.
Values for `DACO_ENCRYPTION_KEY` and `DCC_MAILING_LIST` will need to be added to vault
Email subject line is TBD
=> ✨ 95 - daco2ego encrypted email

src/domain/service.ts, src/domain/state.ts, src/test/state.spec.ts
Adds CLOSED state change
Prevents modifying apps in closed state
Prevents downloading assets from a closed app if it wasn't already approved
Cannot close an app in REVIEW state
=> ✨ 161 - Add CLOSED state functionality

src/domain/state.ts
forgot to remove the push to updates array in #167
=> remove closedBy record from updates audit

src/domain/state.ts, src/domain/validations.ts, src/test/state.spec.ts
Adds validation for collaborator emails when the applicant is updated, applicant info takes precedence.
This is separate from the validation against applicant when a collaborator is added/updated.
=> 🐛 151 -  applicant collab email validation

migrations/20210922165633-add_country_to_search_field_values.js, src/domain/interface.ts, src/domain/service.ts, src/domain/state.ts
Adds country to ApplicationSummary.
Adds country to search terms and sort fields.
Migration to add country to `searchValues` in existing applications.
=> ✨ 180 - Add country to app summary, with search and sort

package.json, src/domain/interface.ts, src/domain/service.ts, src/resources/swagger.yaml
=> 🔖 Rc/0.46.0

src/domain/service.ts, src/resources/swagger.yaml, src/routes/applications.ts
Adds endpoint to search a logged-in user's applications where they are a collaborator.
Small fix for typescript error on catch clause.
=> ✨ 210 - add collaborator apps search endpoint

package.json, src/domain/interface.ts, src/domain/service.ts, src/resources/swagger.yaml
=> 🔖 Rc/0.48.0

src/domain/interface.ts, src/domain/service.ts, src/domain/state.ts, src/resources/swagger.yaml, src/routes/applications.ts, src/utils/misc.ts
Adds endpoint for admin tsv download
Simplest approach for now: retrieves all app updates and then sorts by date
Adds endpoint to swagger docs
=> ✨ 227 - Add app history download endpoint

src/domain/state.ts, src/routes/applications.ts
Fixes days elapsed calculation, will ignore time of update. i.e. ensures a "next day" scenario will show as `1` day elapsed when diff is less than 24hrs.
=> 🐛 227 - Fix days elapsed

src/domain/validations.ts
Fixes logic for duplicate pub error
Allows multiple errors for pubs
Adds custom error text in url validation to support using backend errors in ui
=> 🐛 270 - fix dup publications errs

src/config.ts, src/domain/service.ts, src/emails/access-expiring.ts, src/test/emails.spec.ts
Adds generic email for expiring applications
Adds config values for expiry durations, renewal access guide
Emails will be sent via cron jobs, as in #250 and #251
=> ✨ 231 - Add app expiring email, expiry config values

.env.example, src/domain/service.ts, src/emails/access-expiring.ts, src/emails/access-has-expired.ts, src/emails/application-approved.ts, src/emails/closed-approved.ts, src/emails/collaborator-notification.ts, src/emails/collaborator-removed.ts, src/emails/common.ts, src/test/emails.spec.ts
Adds email + send func for Access Expired.
Adds ability for custom subtitle on access details section of Approval Details func
Updates env.example with durations vars
=> ✨ 232 - access expired email

Jenkinsfile.groovy, src/domain/state.ts, src/test/state.spec.ts
after updating an application that is in DRAFT state because of invalid
PA in collaborator and fixing that collaborator
it should go back to SIGN and SUBMIT state
=> updating collaboratos to enable sign submit

src/domain/service.ts
Show `isAttestable` in app summary for all states, like in single app view
=> show isAttestable for all app states

src/config.ts, src/domain/service.ts, src/emails/access-expiring.ts, src/emails/application-approved.ts, src/emails/attestation-required.ts, src/emails/collaborator-notification.ts, src/emails/common.ts, src/test/emails.spec.ts
Adds attestation required email
- extra prop for approvalDetailsBox to allow for custom label width (not a great solution, but wanted to modify as little as possible with email structure)
- adds attestation guide to config
=> ✨ 228 - Add attestation required email, guide link

src/domain/service.ts, src/emails/application-paused.ts, src/test/emails.spec.ts
Adds app paused email + send function
Will be hooked up to cron job in #239
=> ✨ 229 - Add application paused email

src/domain/service.ts, src/domain/state.ts
- Prevent approval emails on attestation
- add attested email trigger to updateApp func
- placeholder todo for attestation email
- reset `pauseReason` on paused -> approved transition
=> 240 - fix email triggers on attestation

src/config.ts, src/domain/service.ts, src/emails/attestation-received.ts, src/test/emails.spec.ts
Adds email for user attestation
Fixes check for attestation event
=> ✨ 230 - Add attestation received email

src/domain/interface.ts, src/domain/state.ts, src/domain/validations.ts, src/test/state.spec.ts
Change attestation req value to boolean value instead of date, remove date validation
- updates tests
=> ♻️  341 - change attest req value to boolean

package.json
=> 🔖 Rc/1.6.0

src/domain/interface.ts, src/domain/state.ts, src/test/utils.spec.ts
Removes code related to a previous renewal flow approach.
=> 🔥 remove old renewal flow code

src/domain/service/applications/index.ts, src/domain/state.ts, src/jobs/expireAppCheck.ts, src/jobs/runAllJobs.ts, src/test/example_job_queries.ts, src/test/state.spec.ts, src/test/utils.spec.ts, src/utils/calculations.ts
Implements expiry batch job
- `EXPIRED` transition for approved and paused applications
- expiry email trigger
- `isExpirable` calc util
- unit tests for state transition
=> ✨ 252 - add expiry batch job

src/domain/service/emails.ts, src/emails/review-new.ts, src/emails/review-renewal.ts, src/emails/review-revised.ts, src/test/emails.spec.ts
Adds email for when a renewal application is submitted for review
- if a renewal is re-submitted for revisions, it will trigger the "revised application" for review email
=> ✨ 233 - add renewal review email

src/domain/service/applications/index.ts
TIL lodash treats dates as "empty" values...so replaced with a logical not
=> 🐛 393 - fix attestation email trigger check

src/domain/interface.ts, src/domain/service/applications/search.ts, src/domain/state.ts, src/utils/misc.ts
Adds `expiredEventDateUtc` field parsed from updates array for FE convenience when displaying expiry info.
=> ✨ Add expiredEventDate as calculated field for FE

src/domain/state.ts
Prevent collaborator deletion when app state implies the section is locked
UI portion in https://github.com/icgc-argo/dac-ui/pull/684
=> 🐛 416 - prevent delete collab when state locks section

src/jobs/attestationRequiredNotification.ts, src/jobs/expireAppCheck.ts, src/jobs/firstExpiryNotification.ts, src/jobs/pauseAppCheck.ts, src/jobs/secondExpiryNotification.ts
Just some refactoring to match the convention used in #378
=> ♻️  some refactoring and func name changes

src/domain/service/applications/index.ts, src/domain/service/emails.ts
Send access removed notifications to collaborators when an app transitions from `APPROVED` to `PAUSED` or from `APPROVED` to `EXPIRED`
=> ✨ 426 - Send collab emails when app is expired, paused

src/domain/interface.ts, src/resources/swagger.yaml
Updates for Application and ApplicationSummary responses. Adds ApplicationBase schema
- fixes some parsing errors
- cleanup of defunct endpoints
- removes `submittedAtUtc` field from `Application` interface as it is included in the `ApplicationBaseFields` interface
=> 📝 swagger doc updates for application and app summary

package.json
adds fix for configurable storage region
=> 🔖 Rc/1.8.9

Dockerfile
forgot to update the command in the previous pr, to look for `server.ts` under `/dist/src`
=> update dockerfile cmd to use correct dir
